CHANGELOG.md
build.gradle
src/main/java/com/ericsson/eiffel/remrem/semantics/SemanticsService.java
src/main/java/com/ericsson/eiffel/remrem/semantics/events/Event.java
src/main/java/com/ericsson/eiffel/remrem/semantics/validator/EiffelValidator.java
src/test/java/com/ericsson/eiffel/remrem/semantics/ServiceTest.java
src/test/resources/input/ActivityFinishedInvalid.json

Aslo added CHANGELOG.md file to keep track of changes and added unit tests for negative tests.

Removed lombok dependency, improved logging and results to caller.

---

CHANGELOG.md
build.gradle
src/main/java/com/ericsson/eiffel/remrem/semantics/SemanticsService.java
src/test/java/com/ericsson/eiffel/remrem/semantics/ServiceTest.java

- Implemented getServiceName
- Implemented validateMsg
- added remrem-protocol-interface

Get service name and Validate message methods implementation

---

CHANGELOG.md
build.gradle
src/main/java/com/ericsson/eiffel/remrem/semantics/EiffelEventType.java
src/main/java/com/ericsson/eiffel/remrem/semantics/SemanticsService.java
src/test/java/com/ericsson/eiffel/remrem/semantics/ServiceTest.java

Improved exception handling functionality for message type mismatch
- added functionality to display supported event types if message type mismatched

Improved exception handling functionality for message type mismatch

---

src/main/java/com/ericsson/eiffel/remrem/semantics/SemanticsService.java

Implemented functionality to accept case insensitive eventype from query params in generate

Fixed eventType mismatch issue while generating events

---

CHANGELOG.md
build.gradle
src/main/java/com/ericsson/eiffel/remrem/semantics/SemanticsService.java

Updated build.gradle and changelog.md files

Update build.gradle and changelog.md files

---

CHANGELOG.md
build.gradle
src/main/resources/templates/eiffelactivityfinishedevent.json
src/main/resources/templates/eiffelalertacknowledgedevent.json
src/main/resources/templates/eiffelalertceasedevent.json
src/main/resources/templates/eiffelalertraisedevent.json
src/main/resources/templates/eiffelservicedeployedevent.json

Removed serializer information from event tempaltes

Removed serializer information from event tempaltes

---

build.gradle

Updated dependencies versions

---

howToUseSemantics.html
index.html

Updated documenatation as part of migration from gradle to maven

Updated documenatation as part of migration from gradle to maven

---

src/main/java/com/ericsson/eiffel/remrem/semantics/SemanticsService.java
src/main/java/com/ericsson/eiffel/remrem/semantics/clone/PrepareLocalEiffelSchemas.java
src/test/java/com/ericsson/eiffel/remrem/semantics/ServiceTest.java

Hi there,
I wrote this bot based on the top 10 most misspelled english words.
(https://blog.oxforddictionaries.com/2016/08/02/corpus-misspellings/)
The bot queries, forks, clones, fixes and commits but I manually create the PRs.
All the best,
Jimmy

Fixed Spelling.

---

CHANGELOG.md
pom.xml
src/main/java/com/ericsson/eiffel/remrem/semantics/validator/EiffelValidator.java

Added changes to validate link types  while generating events

Added changes to allow valid eiffel types only while generating events

---

CHANGELOG.md
pom.xml

updated parent version from 0.0.5 to 0.0.6.

updated parent version from 0.0.5 to 0.0.6.

---

CHANGELOG.md
pom.xml

Updated Change
it.
(d) I understand and agree …

Updated Changelog.md 

---

CHANGELOG.md
README.md
pom.xml

Changed link from http://eiffel-community.github.io to https://eiffel-community.github.io .
Upgraded eiffel-remrem-protocol-interface version from 1.0.0  to 1.0.1.
(c) …

Upgraded eiffel-remrem-protocol-interface version to 1.0.1.

---

CHANGELOG.md
pom.xml

Parent group changed from Ericsson to Eiffel community
person who certified (a), (b) or (c) and I have not …

Parent group changed from Ericsson to Eiffel community

---

howToUseSemantics.html
index.html
javascripts/eventTypes.js
routingAndBindingKeyConcepts.html

Added EiffelIssueDefinedEvent in the templates to download.
person who certified (a), (b) or (c) and I have …

Changes made to add EiffelIssueDefinedEvent to the templates

---

CHANGELOG.md
pom.xml
src/main/java/com/ericsson/eiffel/remrem/semantics/SemanticsService.java
src/test/java/com/ericsson/eiffel/remrem/semantics/ServiceTest.java
src/test/resources/MANIFEST.MF

Fixed issues when generating events because of false check for semantics purl or not
person who certified …

Fixed issues when generating events because of false check for semantics purl or not

---

CHANGELOG.md
pom.xml
src/main/java/com/ericsson/eiffel/semantics/events/Event.java

it.
(d) I understand and agree that this …

Fix for RemRem Generate Eiffel events with wrong  UTC

---

CHANGELOG.md
pom.xml
src/main/java/com/ericsson/eiffel/semantics/events/EiffelActivityStartedEventMeta.java
src/main/java/com/ericsson/eiffel/semantics/events/EiffelActivityTriggeredEventData.java
src/main/java/com/ericsson/eiffel/semantics/events/EiffelActivityTriggeredEventMeta.java
src/main/resources/schemas/input/EiffelActivityStartedEvent.json
src/main/resources/schemas/input/EiffelActivityTriggeredEvent.json
src/test/resources/input/ActivityStarted.json
src/test/resources/input/ActivityTriggered.json
src/test/resources/output/ActivityStarted.json
src/test/resources/output/ActivityTriggered.json

Security updates are added in couple of events in edition-agen-1 version

Security updates are added in couple of events in edition-agen-1 version

---

howToUseSemantics.html
index.html
javascripts/download.js
routingAndBindingKeyConcepts.html

Updated the download links for events from Ericsson to Eiffel-community

Updated the download links for events from Ericsson to Eiffel-community

---

CHANGELOG.md
pom.xml
src/main/resources/templates/eiffelactivitystartedevent.json
src/main/resources/templates/eiffelactivitytriggeredevent.json

Updated few files in templates with proper data

Updated few files in templates with proper data

---

CHANGELOG.md
pom.xml

Uplifted eiffel-remrem-parent and eiffel-remrem-protocol-interface to latest versions.
person who certified …

Uplifted eiffel-remrem-parent and eiffel-remrem-protocol-interface to latest versions.

---

.travis.yml
CHANGELOG.md
pom.xml

it.
(d) I understand and agree that this …

Uplifted eiffel-remrem-parent version from 2.0.1 to 2.0.2.

---

CHANGELOG.md
pom.xml

Uplifted eiffel-remrem-protocol-interface version from 2.0.2 to 2.0.3.
Uplifted eiffel-remrem-parent version from 2.0.2 to 2.0.3.
Resolve security vulnerability issue. …

Uplifted REMReM parent and protocol-interface versions .

---

CHANGELOG.md
pom.xml

Uplifted eiffel-remrem-parent version from 2.0.3 to 2.0.4
Uplifted eiffel-remrem-protocol-interface version from 2.0.3 to 2.0.4.
resolve security vulnerability issue.
(c) …

Uplifted REMReM parent and protocol-interface versions.

---

CHANGELOG.md
pom.xml

Updated parent version in semantics
it.
(d) I …

updated parent version

---

CHANGELOG.md
pom.xml

Uplifted httpclient version to 4.5.13
it.
(d) …

Uplifted httpclient dependency version

---

CHANGELOG.md
pom.xml

https://github.com/eiffel-community/eiffel-remrem-semantics/issues/151
Uplifted remrem-parent version from 2.0.7 to 2.0.8
Uplifted remrem-protocol interface version from 2.1.2 to 2.1.3 …

Uplifted remrem-parent version from 2.0.7 to 2.0.8 and remrem-protocol interface version from 2.1.2 to 2.1.3

---

pom.xml

Changes necessary to compile and run under Open JDK 17
person who certified (a), (b) or (c) and I have not …

Preparation for Open JDK 17

---

CHANGELOG.md
pom.xml

Uplift Mockito framework to the latest available, i.e. 5.3.1.
Version 5.x.x brings several benefits and simplifications.
(c) The contribution was provided directly to me …

Uplift to Mockito 5.3.1

---

pom.xml
src/main/resources/templates/eiffelartifactpublishedevent.json
src/main/resources/templates/eiffelcompositiondefinedevent.json

Fixes https://github.com/eiffel-community/eiffel-remrem-generate/issues/203
Event versions fixed in the template to match with the corresponding schema.
(c) The …

Event templates versions not match with schema versions.

---

pom.xml
src/main/java/com/ericsson/eiffel/remrem/semantics/SemanticsService.java

There's a need to use version 2.1.0 of this library with the latest version of eiffel-remrem-generate and eiffel-remrem-publish. However, these services use/expect eiffel-remrem-protocol 2.2.0 and they fail when using eiffel-remrem-semantics 2.1.0.
eiffel-remrem-semantics needs to implement new methods introduced by interface MsgService in eiffel-remrem-protocol 2.2.0.
license and I have the right under that license to …

Uplift version 2.1.0 to eiffel-remrem-protocol 2.2.0

---

jitpack.yml
pom.xml
src/main/java/com/ericsson/eiffel/remrem/semantics/SemanticsService.java

JitPack uses JDK 1.8 as a default. If other JDK should be used, jitpack.yml must be included in repository root.
Add jitpack.yml file to project.
(c) The contribution was …

Add jitpack.yml to use OpenJDK 17 for JitPack build

---

.github/dependabot.yml

Added dependabot.yml for actions 
it.
(d) I …

Added dependabot.yml for actions 

---

CHANGELOG.md
jitpack.yml
pom.xml

Ensure Eclipse Temurin is used to build the library
person who certified (a), (b) or (c) and I have not …

Introduce jitpack.yml with temurin 17.0.5

---

.github/workflows/main.yml
README.md
pom.xml

Update code coverage with coveralls and build badge with github actions
person who certified (a), (b) or …

Update code coverage with coveralls and build badge with github actions

---

CHANGELOG.md
jitpack.yml
pom.xml
src/main/resources/templates/eiffelalertacknowledgedevent.json
src/test/resources/input/AlertAknowledgedEvent.json

Fixes https://github.com/eiffel-community/eiffel-remrem-publish/issues/303.
A typo fixed in event template. …

False positive test pass
